# Generated by Django 3.2.4 on 2022-10-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='User Code'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
