# Generated by Django 3.2.4 on 2022-05-23 17:10

import base.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(null=True, storage=base.storages.PublicMediaStorage(), upload_to='', verbose_name='User Avatar'),
        ),
    ]
