# Generated by Django 3.2.4 on 2022-05-23 17:16

import base.storages
from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.FileField(default=user_management.models.default_image, null=True, storage=base.storages.PublicMediaStorage(), upload_to=user_management.models.get_image_filepath, verbose_name='User Avatar'),
        ),
    ]
