# Generated by Django 3.2.4 on 2022-10-11 07:18

import base.storages
import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_code', models.CharField(default=blog_app.models._comment_code, max_length=15, unique=True, verbose_name='Comment Code')),
                ('comment_content', models.TextField(default='', max_length=5000, null=True, verbose_name='Comment Content')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='Comment Time')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_code', models.CharField(default=blog_app.models._image_code, max_length=30, unique=True, verbose_name='Image Code')),
                ('image_content', models.FileField(default=blog_app.models.default_image, null=True, storage=base.storages.PublicMediaStorage(), upload_to=blog_app.models.get_image_filepath, verbose_name='Image Content')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_code', models.CharField(default=blog_app.models._post_code, max_length=15, unique=True, verbose_name='Post Code')),
                ('post_title', models.CharField(max_length=255, unique=True, verbose_name='Post Title')),
                ('post_summary', models.TextField(default='', max_length=500, null=True, verbose_name='Post Summary')),
                ('post_public', models.BooleanField(default=True, verbose_name='Post Public')),
                ('post_likes', models.IntegerField(default=0, verbose_name='Post Likes')),
                ('post_views', models.IntegerField(default=0, verbose_name='Post Views')),
                ('post_edited', models.BooleanField(default=False, verbose_name='Post Editted')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Post Date')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_code', models.CharField(default=blog_app.models._comment_code, max_length=15, unique=True, verbose_name='Reply Code')),
                ('reply_content', models.TextField(default='', max_length=5000, null=True, verbose_name='Reply Content')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='reply Time')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_code', models.CharField(default=blog_app.models._post_code, max_length=15, unique=True, verbose_name='Section Code')),
                ('section_title', models.CharField(default='', max_length=255, null=True, verbose_name='Section Title')),
                ('section_content', models.TextField(default='', max_length=10000, null=True, verbose_name='Section Content')),
                ('section_public', models.BooleanField(default=True, verbose_name='Section Public')),
            ],
        ),
    ]
