# Generated by Django 3.2.4 on 2022-10-11 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='section_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_post', to='blog_app.post'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='blog_app.comment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_post', to='blog_app.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='image_related_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='blog_app.post'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_related_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_image', to='blog_app.section'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='blog_app.post'),
        ),
    ]
