# Generated by Django 3.2.4 on 2022-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=0, verbose_name='Post Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_views',
            field=models.IntegerField(default=0, verbose_name='Post Views'),
        ),
    ]
