# Generated by Django 3.2.4 on 2022-05-23 17:05

import base.storages
import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20220520_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_content',
            field=models.ImageField(default=blog_app.models.default_image, null=True, storage=base.storages.PublicMediaStorage(), upload_to=blog_app.models.get_image_filepath, verbose_name='Image Content'),
        ),
    ]
