# Generated by Django 3.2.4 on 2022-05-23 17:16

import base.storages
import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_image_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_content',
            field=models.FileField(default=blog_app.models.default_image, null=True, storage=base.storages.PublicMediaStorage(), upload_to=blog_app.models.get_image_filepath, verbose_name='Image Content'),
        ),
    ]
