# Generated by Django 3.2.4 on 2022-10-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_related_post',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='blog_app.post'),
        ),
    ]
