# Generated by Django 3.2.4 on 2022-10-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_image_image_related_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_finished',
            field=models.BooleanField(default=False, verbose_name='Post Finished'),
        ),
    ]
