# Generated by Django 3.2.4 on 2022-10-31 20:30

import base.storages
import blog_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_post_post_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_code', models.CharField(default=blog_app.models._image_code, max_length=30, unique=True, verbose_name='File Code')),
                ('file_type', models.CharField(default='', max_length=30, unique=True, verbose_name='File Type')),
                ('file_content', models.FileField(default=None, null=True, storage=base.storages.PublicMediaStorage(), upload_to=blog_app.models.get_image_filepath, verbose_name='File Content')),
                ('file_related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_file', to='blog_app.post')),
                ('file_related_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_file', to='blog_app.section')),
            ],
        ),
    ]
