# Generated by Django 3.2.4 on 2022-10-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='', max_length=30, verbose_name='File Type'),
        ),
    ]
