# Generated by Django 3.2.4 on 2022-11-02 06:15

import base.storages
import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_code',
            field=models.CharField(default=blog_app.models._file_code, max_length=30, unique=True, verbose_name='File Code'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.FileField(default=None, null=True, storage=base.storages.PublicMediaStorage(), upload_to=blog_app.models.get_file_filepath, verbose_name='File Content'),
        ),
    ]
